#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 The Movebreak Authors
# SPDX-License-Identifier: GPL-3.0-or-later
"""Install Movebreak for the current user. No administrator rights needed.

    python3 scripts/install.py                       # install into ~/.local
    python3 scripts/install.py --dev                 # run straight from this checkout
    python3 scripts/install.py --uninstall           # remove it, keep your data
    python3 scripts/install.py --uninstall --purge   # remove it and your data

What it installs (with the default prefix, ``~/.local``):

    bin/movebreak                                  launcher script
    lib/movebreak/movebreak/                       the Python package
    share/applications/<APP_ID>.desktop            needed for notifications
    share/dbus-1/services/<APP_ID>.service         lets notification buttons wake the app
    share/icons/hicolor/.../<APP_ID>[-symbolic].svg
    share/metainfo/<APP_ID>.metainfo.xml

The Flatpak manifest runs this script with ``--flatpak --prefix=/app``.
Only the Python standard library is used, so it runs on any Linux system.
"""

from __future__ import annotations

import argparse
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE_PACKAGE = ROOT / "src" / "movebreak"
DATA = ROOT / "data"

DEPENDENCY_CHECK = """
import gi
gi.require_version("Gtk", "4.0")
gi.require_version("Adw", "1")
from gi.repository import Adw, Gtk
version = (Adw.get_major_version(), Adw.get_minor_version())
print("GTK %d.%d, libadwaita %d.%d" % (Gtk.get_major_version(), Gtk.get_minor_version(), *version))
raise SystemExit(0 if version >= (1, 5) else 3)
"""

LAUNCHER = """\
#!/bin/sh
# Movebreak launcher, generated by scripts/install.py. Do not edit; reinstall instead.
MOVEBREAK_LAUNCHER="@LAUNCHER@"
export MOVEBREAK_LAUNCHER
PYTHONPATH="@LIBDIR@${PYTHONPATH:+:$PYTHONPATH}"
export PYTHONPATH
exec "@PYTHON@" -m movebreak "$@"
"""

HELP_MISSING_DEPENDENCIES = """
Movebreak needs PyGObject with GTK 4 and libadwaita 1.5 or newer, and this
Python ({python}) cannot load them:

{details}

  Fedora:         sudo dnf install python3-gobject gtk4 libadwaita
  Ubuntu/Debian:  sudo apt install python3-gi gir1.2-gtk-4.0 gir1.2-adw-1

Without administrator rights, ask your IT team for those packages, or use the
Flatpak build if Flatpak is installed (see README.md). To install anyway, rerun
with --no-check.
"""


def read_app_id() -> str:
    """The application ID, read from its single source of truth (config.py)."""
    text = (SOURCE_PACKAGE / "config.py").read_text(encoding="utf-8")
    match = re.search(r'^APP_ID = "([A-Za-z0-9_.-]+)"$', text, re.MULTILINE)
    if match is None:
        raise SystemExit("Could not find APP_ID in src/movebreak/config.py")
    return match.group(1)


class Layout:
    """Where every installed file goes."""

    def __init__(self, prefix: Path, app_id: str, dev: bool) -> None:
        self.prefix = prefix
        self.app_id = app_id
        self.bin = prefix / "bin" / "movebreak"
        self.lib = ROOT / "src" if dev else prefix / "lib" / "movebreak"
        share = prefix / "share"
        self.desktop = share / "applications" / f"{app_id}.desktop"
        self.service = share / "dbus-1" / "services" / f"{app_id}.service"
        self.icon = share / "icons" / "hicolor" / "scalable" / "apps" / f"{app_id}.svg"
        self.symbolic = share / "icons" / "hicolor" / "symbolic" / "apps" / f"{app_id}-symbolic.svg"
        self.metainfo = share / "metainfo" / f"{app_id}.metainfo.xml"
        self.applications = share / "applications"
        self.icon_theme = share / "icons" / "hicolor"

    def generated_files(self) -> list[Path]:
        return [self.bin, self.desktop, self.service, self.icon, self.symbolic, self.metainfo]


def default_python(flatpak: bool) -> str:
    if flatpak or Path("/usr/bin/python3").exists():
        return "/usr/bin/python3"
    return sys.executable


def render(template: Path, values: dict[str, str]) -> str:
    text = template.read_text(encoding="utf-8")
    for key, value in values.items():
        text = text.replace(f"@{key}@", value)
    leftover = re.search(r"@[A-Z_]+@", text)
    if leftover:
        raise SystemExit(f"Unreplaced placeholder {leftover.group(0)} in {template}")
    return text


def write(path: Path, content: str, mode: int = 0o644) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(path.name + ".tmp")
    temporary.write_text(content, encoding="utf-8")
    temporary.chmod(mode)
    temporary.replace(path)
    print(f"  {path}")


def check_dependencies(python: str) -> None:
    result = subprocess.run(
        [python, "-c", DEPENDENCY_CHECK], capture_output=True, text=True, check=False
    )
    if result.returncode == 0:
        print(f"Found {result.stdout.strip()}")
        return
    details = (result.stderr.strip().splitlines() or [result.stdout.strip()])[-1]
    raise SystemExit(HELP_MISSING_DEPENDENCIES.format(python=python, details=details))


def install(layout: Layout, python: str, *, dev: bool, flatpak: bool) -> None:
    print(f"Installing Movebreak ({layout.app_id}) into {layout.prefix}")

    if not dev:
        target = layout.lib / "movebreak"
        if target.exists():
            shutil.rmtree(target)
        shutil.copytree(
            SOURCE_PACKAGE, target, ignore=shutil.ignore_patterns("__pycache__", "*.pyc")
        )
        print(f"  {target}/")
        # Precompile, so a read-only install (Flatpak) starts quickly.
        subprocess.run([python, "-m", "compileall", "-q", str(target)], check=False)

    launcher_path = "/app/bin/movebreak" if flatpak else str(layout.bin)
    write(
        layout.bin,
        LAUNCHER.replace("@LAUNCHER@", launcher_path)
        .replace("@LIBDIR@", str(layout.lib))
        .replace("@PYTHON@", python),
        mode=0o755,
    )

    exec_command = "movebreak" if flatpak else str(layout.bin)
    values = {"APP_ID": layout.app_id, "EXEC": exec_command}
    write(layout.desktop, render(DATA / "app.desktop.in", values))
    write(layout.service, render(DATA / "app.service.in", values))
    write(layout.metainfo, render(DATA / "app.metainfo.xml.in", values))
    write(layout.icon, (DATA / "icons" / "app.svg").read_text(encoding="utf-8"))
    write(layout.symbolic, (DATA / "icons" / "app-symbolic.svg").read_text(encoding="utf-8"))

    if not flatpak:
        refresh_caches(layout)


def refresh_caches(layout: Layout) -> None:
    """Help GNOME notice the new files sooner. Optional: failures are ignored."""
    for command in (
        ["update-desktop-database", "-q", str(layout.applications)],
        ["gtk-update-icon-cache", "-q", "-t", "-f", str(layout.icon_theme)],
    ):
        if shutil.which(command[0]):
            subprocess.run(command, check=False, capture_output=True)


def stop_running_instance(app_id: str) -> None:
    if shutil.which("gapplication"):
        subprocess.run(
            ["gapplication", "action", app_id, "quit"], check=False, capture_output=True, timeout=10
        )


def uninstall(layout: Layout, *, purge: bool) -> None:
    print(f"Removing Movebreak ({layout.app_id}) from {layout.prefix}")
    stop_running_instance(layout.app_id)
    for path in layout.generated_files():
        if path.exists():
            path.unlink()
            print(f"  removed {path}")
    managed_lib = layout.prefix / "lib" / "movebreak"
    if layout.lib == managed_lib and managed_lib.exists():
        shutil.rmtree(managed_lib)
        print(f"  removed {managed_lib}/")

    config_home = Path(os.environ.get("XDG_CONFIG_HOME") or Path.home() / ".config")
    autostart = config_home / "autostart" / f"{layout.app_id}.desktop"
    if autostart.exists():
        autostart.unlink()
        print(f"  removed {autostart}")

    data_home = Path(os.environ.get("XDG_DATA_HOME") or Path.home() / ".local" / "share")
    data = data_home / "movebreak"
    if purge and data.exists():
        shutil.rmtree(data)
        print(f"  removed {data}/ (your settings and history)")
    elif data.exists():
        print(f"Kept your settings and history in {data}/ (use --purge to delete them).")
    refresh_caches(layout)


def print_next_steps(layout: Layout) -> None:
    on_path = str(layout.bin.parent) in os.environ.get("PATH", "").split(os.pathsep)
    command = "movebreak" if on_path else str(layout.bin)
    print("\nDone. Next steps:")
    print(f"  1. Open Movebreak from the app grid, or run: {command}")
    print("  2. In Preferences, turn on “Start at Login”.")
    print(f"  3. Check this computer's support:  {command} doctor")
    if not on_path:
        print(f"\nTip: {layout.bin.parent} is not on your PATH; log out and back in, or add it.")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--prefix",
        type=Path,
        default=Path.home() / ".local",
        help="installation prefix (default: ~/.local)",
    )
    parser.add_argument("--dev", action="store_true", help="run the code from this checkout")
    parser.add_argument("--uninstall", action="store_true", help="remove the installation")
    parser.add_argument("--purge", action="store_true", help="with --uninstall: delete your data")
    parser.add_argument("--flatpak", action="store_true", help=argparse.SUPPRESS)
    parser.add_argument("--python", help="Python interpreter to run Movebreak with")
    parser.add_argument("--no-check", action="store_true", help="skip the dependency check")
    args = parser.parse_args(argv)

    prefix = args.prefix.expanduser().resolve()
    layout = Layout(prefix, read_app_id(), args.dev)
    python = args.python or default_python(args.flatpak)

    if args.uninstall:
        uninstall(layout, purge=args.purge)
        return 0
    if not (args.no_check or args.flatpak):
        check_dependencies(python)
    install(layout, python, dev=args.dev, flatpak=args.flatpak)
    if not args.flatpak:
        print_next_steps(layout)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
